package:
  name: pyproj
  version: 3.7.1
  top-level:
    - pyproj
source:
  url: https://github.com/pyproj4/pyproj/archive/refs/tags/3.7.1.tar.gz
  sha256: 3adcc634fe73a8bfab3f226a03980cc24862d27f4e18b77bc39a3e86ad777e85

requirements:
  host:
    - libproj
  run:
    - certifi
    - sqlite3

build:
  script: |
    embuilder build sqlite3 --pic

    export PROJ_VERSION=9.5.1
    export PROJ_DIR=${WASM_LIBRARY_DIR}
    export PROJ_INCDIR=${WASM_LIBRARY_DIR}/include
    export PROJ_LIBDIR=${WASM_LIBRARY_DIR}/lib
    export PROJ_WHEEL=1
    mkdir -p pyproj/proj_dir/share
    cp -r ${WASM_LIBRARY_DIR}/share/proj pyproj/proj_dir/share
  cflags: |
    -sUSE_SQLITE3
  ldflags: |
    -sUSE_SQLITE3
    -lsqlite3
test:
  imports:
    - pyproj

about:
  home: https://github.com/pyproj4/pyproj
  PyPI: https://pypi.org/project/pyproj/
  summary:
    Python interface to PROJ (cartographic projections and coordinate transformations
    library)
  license: MIT
